name: Main branch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run Python programs (1/2)
        run: python src/data_profiler.py data/heart_2022_no_nans_small.csv

      - name: Run Python programs (2/2)
        run: python src/xgboost_model_evaluator.py data/heart_2022_no_nans_small.csv
